env:
    rcloneconfig: "ENCRYPTED[81f2ea42a1bb72f5514f01604e25bb9057eb0b6f1b0f5a18434dd7175df07619a880e75ecb9597e10e69fba44553fe84]"
    tokentl: "ENCRYPTED[635e0f6a0eba8b826946060570abec570da283211dd3be25ba50ff895855fd6f35aa1181acdbbb20ec3331f16cde6bbd]"
    idtl: "ENCRYPTED[34e83ce99a26a43722c25a9237e72beb606357204ef3029e5fe641f449ebd90db2ae3b7a2676bf686c62ffa9606f48db]"

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "I-n-o-k"
       - git config --global user.email "inok.dr189@gmail.com"
       - mkdir -p /~/ccache
       - rclone copy inok:supri/ccache.tar.gz /~ -P
       - cd /~
       - time tar xf ccache.tar.gz
       - cd /~
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - cd /~/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/SuperiorOS/manifest -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/Zooxv/device_xiaomi_juice -b superior device/xiaomi/juice
      - git clone --depth=1 https://github.com/Zooxv/vendor_xiaomi_citrus  --single-branch -b r11 vendor/xiaomi/juice
      - git clone --depth=1 https://github.com/Zooxv/proton-clang -b master prebuilts/clang/host/linux-x86/clang-proton
      - git clone --depth=1 https://github.com/Zooxv/Xiaomi-Fury-Bengal-SD662 --single-branch -b CitrusMoonInline kernel/xiaomi/juice
      # HALS
      - rm -rf hardware/qcom-caf/sm8250/audio
      - rm -rf hardware/qcom-caf/sm8250/display
      - rm -rf hardware/qcom-caf/sm8250/media
      - rm -rf external/json-c
      - rm -rf vendor/qcom/opensource/commonsys-intf/bluetooth
      - rm -rf vendor/qcom/opensource/commonsys/bluetooth_ext
      - rm -rf vendor/qcom/opensource/interfaces
      - git clone --depth=1 https://github.com/I-n-o-k/android_vendor_qcom_opensource_interfaces vendor/qcom/opensource/interfaces
      - git clone --depth=1 https://github.com/I-n-o-k/android_vendor_qcom_opensource_bluetooth_ext vendor/qcom/opensource/commonsys/bluetooth_ext
      - git clone --depth=1 https://github.com/I-n-o-k/android_vendor_qcom_opensource_bluetooth-commonsys-intf vendor/qcom/opensource/commonsys-intf/bluetooth
      - git clone --depth=1 https://github.com/I-n-o-k/hardware_qcom-caf_sm8250_audio hardware/qcom-caf/sm8250/audio
      - git clone --depth=1 https://github.com/I-n-o-k/hardware_qcom-caf_sm8250_display hardware/qcom-caf/sm8250/display
      - git clone --depth=1 https://github.com/I-n-o-k/hardware_qcom-caf_sm8250_media hardware/qcom-caf/sm8250/media
      - git clone --depth=1 https://github.com/LineageOS/android_external_json-c -b lineage-18.1 external/json-c
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip)"
#      - rclone copy /tmp/rom/out/target/product/juice/Nusantara*.zip inok:juice -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Download link http://anu.inok189.workers.dev/juice/$(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip)"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz inok:supri -P
      - echo " "
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
