env:
    rcloneconfig: "ENCRYPTED[81f2ea42a1bb72f5514f01604e25bb9057eb0b6f1b0f5a18434dd7175df07619a880e75ecb9597e10e69fba44553fe84]"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - apt update
       - apt install sudo
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "I-n-o-k"
       - git config --global user.email "cirrus.dr189@gmail.com"
       - mkdir -p /tmp/ccache
       - rclone copy cirrus:Hycon/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/HyconOS/manifest -b eleven -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      # DT/VT/KT/TC
      - git clone --depth=1  https://github.com/Zooxv/device_xiaomi_juice -b eleven device/xiaomi/juice
      - git clone  --depth=1 https://github.com/Zooxv/vendor_xiaomi_citrus  --single-branch -b r11 vendor/xiaomi/juice
      - git clone --depth=1 https://github.com/Zooxv/proton-clang -b master prebuilts/clang/host/linux-x86/clang-proton
      - git clone  https://github.com/Zooxv/Xiaomi-Fury-Bengal-SD662 --depth=1 --single-branch -b CitrusMoonInline kernel/xiaomi/juice
      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - ./collect.sh
#      - ./final.sh
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
#      - rclone copy /tmp/rom/out/target/product/juice/*.zip cirrus:juice -P
      - ./ziping.sh
      - cd /tmp
      - rclone copy ccache.tar.gz cirrus:Hycon -P
      - echo " "
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
